name: Fly Deploy (Staging)
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app to staging
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/develop'
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --config ./fly.staging.toml --remote-only
